// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_v0_assets from "./routes/api/v0/assets.ts";
import * as $api_v0_assets_id_ from "./routes/api/v0/assets/[id].ts";
import * as $api_v0_assets_preview_id_ from "./routes/api/v0/assets/preview/[id].ts";
import * as $assets_id_ from "./routes/assets/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $RemoveButton from "./islands/RemoveButton.tsx";
import * as $UploadButton from "./islands/UploadButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/v0/assets.ts": $api_v0_assets,
    "./routes/api/v0/assets/[id].ts": $api_v0_assets_id_,
    "./routes/api/v0/assets/preview/[id].ts": $api_v0_assets_preview_id_,
    "./routes/assets/[id].tsx": $assets_id_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/RemoveButton.tsx": $RemoveButton,
    "./islands/UploadButton.tsx": $UploadButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
