// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/v0/assets.ts";
import * as $3 from "./routes/api/v0/assets/[id].ts";
import * as $4 from "./routes/api/v0/assets/preview/[id].ts";
import * as $5 from "./routes/assets/[id].tsx";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/RemoveButton.tsx";
import * as $$1 from "./islands/UploadButton.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/v0/assets.ts": $2,
    "./routes/api/v0/assets/[id].ts": $3,
    "./routes/api/v0/assets/preview/[id].ts": $4,
    "./routes/assets/[id].tsx": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/RemoveButton.tsx": $$0,
    "./islands/UploadButton.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
